---
sudo: required
dist: xenial
language: python
env:
 - LINT=1
 - IMAGE="ubuntu:trusty"
 - IMAGE="ubuntu:xenial"
 - IMAGE="ubuntu:artful"
 - IMAGE="images:ubuntu/bionic"
 - IMAGE="images:centos/6"
 - IMAGE="images:centos/7"
script:
 - if [ ! -z ${LINT} ]; then echo "Hello, world!"; fi
# setup dependencies here to save time on simpler test environments
# wait for lxd socket to be ready after snap installation
# sudo back to ourself to activate lxd group membership
 - if [ ! -z ${IMAGE} ]; then
      sudo apt-get -qq update && sudo apt remove --purge lxd lxd-client
      sudo rm -Rf /var/lib/lxd
      sudo apt-get -y install snapd;
      sudo snap install lxd;
      sudo systemctl stop snap.lxd.daemon.service
      sudo rm -Rf /var/snap/lxd/common/lxd/*
      systemctl start snap.lxd.daemon.service
      sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment';
      while [ ! -S /var/snap/lxd/common/lxd/unix.socket ]; do echo "Waiting for LXD socket...";sleep 0.2;done;
      sudo lxd init --auto;
      sudo usermod -a -G lxd travis;
   fi
 - if [ ! -z ${IMAGE} ]; then
      sudo su travis -c 'lxc launch ${IMAGE} mymachinecontainer';
      sudo su travis -c 'lxc exec mymachinecontainer -- sh -c "lsb_release -a || cat /etc/redhat-release"';
   fi
