---
sudo: required
dist: trusty
language: python
env:
 - LINT=1
 - IMAGE="ubuntu:precise"
 - IMAGE="ubuntu:trusty"
 - IMAGE="ubuntu:xenial"
 - IMAGE="ubuntu:yakkety"
 - IMAGE="images:ubuntu/zesty"
 - IMAGE="images:centos/6"
 - IMAGE="images:centos/7"
script:
 - if [ ! -z ${LINT} ]; then echo "Hello, world!"; fi
# setup dependencies here to save time on simpler test environments
# sudo back to ourself to activate lxd group membership
 - if [ ! -z ${IMAGE} ]; then
      sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable;
      sudo apt-get -qq update;
      sudo apt-get -y install lxd;
      sudo lxd init --auto;
      sudo usermod -a -G lxd travis;
      sudo su travis -c 'lxc network create lxdbr0';
      sudo su travis -c 'lxc network attach-profile lxdbr0 default eth0';
   fi
 - if [ ! -z ${IMAGE} ]; then
      sudo su travis -c 'lxc launch ${IMAGE} mymachinecontainer';
      sudo su travis -c 'lxc exec mymachinecontainer -- sh -c "lsb_release -a || cat /etc/redhat-release"';
   fi
